### ISSUE TITLE
API：get_group_list无法获取群列表

### ISSUE THREAD

**Issue by qwe0099001** [Yiwen-Chan/OneBot-YaYa#1]
用易语言调用的，用的正向Websocket
返回{"status":"ok","retcode":0,"data":[{"group_id":0,"group_name":"unknow","member_count":0,"max_member_count":0}],"echo":123}

**Comment by kanrichan** [comment]
Fix at [e7f7149](https://github.com/Yiwen-Chan/OneBot-YaYa/commit/e7f71492af5eb325b253b70ae6e8e4fb2286e57a)
Please download a new release
