### ISSUE TITLE
无法发送语音信息

### ISSUE THREAD

**Issue by foxwhite25** [Yiwen-Chan/OneBot-YaYa#12]
[CQ:record,file=https://github.com/foxwhite25/next.js/raw/master/144-0000.mp3]
在go-cqhttp发送这个cq码时
![5KW%F8KX%KO8E(3L(W~DR4M](https://user-images.githubusercontent.com/39846845/106506024-f63fd480-647d-11eb-9376-0f635364a9a7.png)
在先驱发送这个cq码时
![KT5I O$)AF1XC91$IA0)IDV](https://user-images.githubusercontent.com/39846845/106506064-048df080-647e-11eb-9fb8-673666cdf249.png)
好像会变成[pic=路径]这样的信息，无法发送语音
尝试过将先驱改名成英文路径，但是也是一样

**Comment by kanrichan** [comment]
已在action中的版本修复
https://github.com/Yiwen-Chan/OneBot-YaYa/suites/1938536163/artifacts/38276210
