### ISSUE TITLE
lifecycle事件传入变量名不一致

### ISSUE THREAD

**Issue by 11551107C1** [Yiwen-Chan/OneBot-YaYa#15]
目前不知道为什么lifecycle传入的变量名是self_ID而不是nonebot事件本身的self_id，会导致整个程序报错

log大概长这样：
Failed to handle event. Raw: {'meta_event_type': 'lifecycle', 'post_type': 'meta_event', 'self_ID': (机器人qq号), 'sub_type': 'connect', 'time': 1617883945}
（跳过一堆东西）
pydantic.error_wrappers.ValidationError: 1 validation error for Event
self_id
  field required (type=value_error.missing)

我自己搞了半天发现大概是因为server\websocket_server.go里面的ServeHTTP函数输入的参数名不对 但因为不知道编译用的gcc版本（加上我又很菜）无法帮忙debug
希望可以看看这个问题（乖巧）

**Comment by 11551107C1** [comment]
如果这个不是bug的话也请告诉我该怎么做 我实在太菜了（小声

**Comment by kanrichan** [comment]
打错字了，稍后会发版
