### ISSUE TITLE
API:handle_quick_operation未实现

### ISSUE THREAD

**Issue by twfx1207** [Yiwen-Chan/OneBot-YaYa#3]
使用反向ws连接yobot时发现日志报错，yobot的返回信息调用了handle_quick_operation这个API，但是插件抛出了no such api错误：
```
BOT <- ws://172.20.0.1:8080/ws/ API: .handle_quick_operation Params: {"action": ".handle_quick_operation_async", "params": {"context": {"anonymous": null, "font": 0, "group_id": *, "message": "version", "message_id": 1262, "message_type": "group", "post_type": "message", "raw_message": "version", "self_id": *, "sender": {"age": 0, "area": "", "card": "unknown", "level": "", "nickname": "unknown", "role": "admin", "sex": "unknown", "title": "unknown", "user_id": *}, "sub_type": "normal", "time": 1607966336, "user_id": *}, "operation": {"reply": "yobot[v3.6.7]\u63d2\u4ef6\u7248", "at_sender": false}}, "echo": {"seq": 48417}}
ws://172.20.0.1:8080/ws/ <- {"status":"failed","retcode":100,"data":"no such api","echo":{"seq":48417}}
```
另外测试过程中发现使用CQ码发送网络图片时动作不正常，获得的信息是一串pic代码而非图片。
sender字段中的发送者信息也无法正常获取（只提供了unknown）
后台发送信息：
```
BOT <- ws://172.20.0.1:8080/ws/ API: send_msg Params: {"action": "send_msg", "params": {"font": 0, "message": "[CQ:image,file=https://i.pixiv.cat/img-original/img/2018/12/07/20/08/36/72007386_p15.jpg]", "message_id": 29101, "message_type": "private", "post_type": "message", "raw_message": "\u6765\u4efd\u8272\u56fe", "self_id": *, "sender": {"age": "unknown", "nickname": "unknown", "sex": "unknown", "user_id": *, "card": "unknown"}, "sub_type": "friend", "time": 1607967326, "user_id": *}, "echo": {"seq": 48470}}
```
实际收到的信息：
```
チノ  02:35:29
[pic={1663652635-3023475402-0332D85CDEE105B506A388BA5852A464}.jpg]
```

**Comment by kanrichan** [comment]
> 使用反向ws连接yobot时发现日志报错，yobot的返回信息调用了handle_quick_operation这个API，但是插件抛出了no such api错误：

此API已在master分支中新增，暂时未发布release，可以在下面链接中下载
https://github.com/Yiwen-Chan/OneBot-YaYa/suites/1669827685/artifacts/31131922

**Comment by kanrichan** [comment]
> sender字段中的发送者信息也无法正常获取（只提供了unknown）

sender字段中提供unknown为暂时的，因为还没建立对应的数据库

**Comment by kanrichan** [comment]
> 另外测试过程中发现使用CQ码发送网络图片时动作不正常，获得的信息是一串pic代码而非图片。

这个在我测试中并没有发现异常，如果仍有发现这种情况请继续提交issue

**Comment by twfx1207** [comment]
> > 另外测试过程中发现使用CQ码发送网络图片时动作不正常，获得的信息是一串pic代码而非图片。
> 
> 这个在我测试中并没有发现异常，如果仍有发现这种情况请继续提交issue

刚才重新测试了一下，因为测试环境的剪贴板有些问题就直接上截图了（已抹去无关日志）
![image](https://user-images.githubusercontent.com/15899807/102291881-64d8d980-3f87-11eb-9854-5da95de8a6d0.png)
CQ码的格式类似于：
```
[CQ:image,file=https://i.pixiv.cat/img-original/img/2018/12/07/20/08/36/72007386_p15.jpg]
```
图片上传看上去正常处理了，但是最后图并没有传过来。

**Comment by kanrichan** [comment]
> 图片上传看上去正常处理了，但是最后图并没有传过来。

先驱在上传图片的过程中可能会遇到吞图片的情况，但是一般在启动框架后首次发图的时候出现
假如一直没办法上传图片可以先等待片刻后再重启框架，如果仍然发不出去大概是被风控了
