### ISSUE TITLE
消息事件不能获取发送者昵称

### ISSUE THREAD

**Issue by huisunan** [Yiwen-Chan/OneBot-YaYa#5]
![image](https://user-images.githubusercontent.com/30598579/102683966-96fc6c80-420f-11eb-9bac-d41e81412a30.png)
昵称是unknown的
年龄字段是数字类型的，unknown后是字符串类型

**Comment by kanrichan** [comment]
https://github.com/Yiwen-Chan/OneBot-YaYa/suites/2211232505/artifacts/45732067
1.2.0版本开始解决此问题
