### ISSUE TITLE
Json的null值都是字符串的"null"

### ISSUE THREAD

**Issue by huisunan** [Yiwen-Chan/OneBot-YaYa#7]
Json的null值都是字符串的"null"，可以修改一下吗

**Comment by kanrichan** [comment]
具体是哪个字段呢，或者有没有详细的复现方法呢

**Comment by huisunan** [comment]
{
	"interval": "10000",
	"meta_event_type": "heartbeat",
	"post_type": "meta_event",
	"self_id": "318326762",
	"status": "null",
	"time": "1610023751"
}
心跳包里的status

**Comment by kanrichan** [comment]
初步修复 [✏️ Promote heartbeats status](https://github.com/Yiwen-Chan/OneBot-YaYa/commit/ecb96da188afe727dd6621293191eb082b72170d)

**Comment by kanrichan** [comment]
下载 [OneBot-YaYa](https://github.com/Yiwen-Chan/OneBot-YaYa/suites/1785316701/artifacts/34145218)
